services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb:v1
    env_file: .env
    secrets:
      - db_root_password
      - db_password
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$(tr -d '\r\n' < /run/secrets/db_root_password)"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress:v1
    env_file: .env
    secrets:
      - db_password
      - credentials
    healthcheck:
      test: ["CMD", "test", "-f", "/var/www/html/wp-login.php"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    depends_on:
      mariadb:
        condition: service_healthy
    restart: always

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx:v1
    env_file: .env
    depends_on:
      wordpress:
        condition: service_healthy
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html:ro
    networks:
      - inception
    restart: always

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/viljar/data/mariadb

  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/viljar/data/wordpress

networks:
  inception:
    name: inception
    driver: bridge

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
  credentials:
    file: ../secrets/credentials.txt